# Generated by Django 5.2 on 2026-09-25 03:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Item')),
                ('placement', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(default='Pcs', max_length=20)),
                ('allocation', models.CharField(choices=[('all', 'All colors'), ('color', 'By color'), ('size', 'By size'), ('color_size', 'Color & size')], default='color', max_length=12)),
                ('consumption', models.DecimalField(decimal_places=6, default=0, max_digits=14, verbose_name='Consumption / pc')),
                ('color_combo', models.CharField(blank=True, max_length=60, verbose_name='Color combination')),
                ('spec', models.CharField(blank=True, max_length=60, verbose_name='Size / spec')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BOMRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_color', models.CharField(blank=True, max_length=60)),
                ('size_idx', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color_combo', models.CharField(blank=True, max_length=60)),
                ('spec', models.CharField(blank=True, max_length=60)),
                ('consumption', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('qty_override', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='orders.bomitem')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=40, verbose_name='Buyer PO')),
                ('buyer', models.CharField(max_length=100)),
                ('factory', models.CharField(blank=True, max_length=100)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='running', max_length=10)),
                ('stage', models.PositiveSmallIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('cost_per_pc', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Cost / pc')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_extras', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='bomitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='orders.order'),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Item / Description')),
                ('qty', models.PositiveIntegerField(verbose_name='Qty (pcs)')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Price / pc')),
                ('size_type', models.CharField(blank=True, choices=[('letter', 'Letter sizes (S – 5XL)'), ('number', 'Number sizes (30 – 44)')], max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='bomitem',
            name='line',
            field=models.ForeignKey(blank=True, help_text='Blank = all styles of the order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='orders.orderline', verbose_name='Style'),
        ),
        migrations.CreateModel(
            name='AssortmentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=60)),
                ('qtys', models.JSONField(default=list)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assortment', to='orders.orderline')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=100)),
                ('po_date', models.DateField(default=django.utils.timezone.localdate)),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Required delivery')),
                ('pi_no', models.CharField(blank=True, max_length=60, verbose_name='PI no.')),
                ('lc_no', models.CharField(blank=True, max_length=60, verbose_name='LC no.')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='ETD')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partial', 'Partly received'), ('received', 'Received')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_pos', to='orders.order')),
            ],
            options={
                'verbose_name': 'Supplier PO',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPOLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, max_length=60)),
                ('description', models.CharField(max_length=150)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('spec', models.CharField(blank=True, max_length=60)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('bom_rows', models.ManyToManyField(blank=True, related_name='po_lines', to='orders.bomrow')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.supplierpo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
