# Generated by Django 5.2 on 2026-10-05 14:38

from django.db import migrations, models


GUESSES = [
    ('fabric', ['fabric', 'twill', 'pocketing', 'interlining', 'denim', 'jersey', 'fleece', 'poplin', 'canvas']),
    ('labels', ['label', 'hangtag', 'hang tag', ' tag', 'tag ']),
    ('packing', ['poly', 'carton', 'scotch', 'gum tape', 'blister']),
]


def guess_types(apps, schema_editor):
    """Existing materials all start as 'trims'; guess the obvious ones from
    their names. A PO whose materials all share one type takes that type."""
    BOMItem = apps.get_model('orders', 'BOMItem')
    SupplierPO = apps.get_model('orders', 'SupplierPO')
    for item in BOMItem.objects.all():
        name = f' {item.name.lower()} '
        for category, words in GUESSES:
            if any(word in name for word in words):
                item.category = category
                item.save(update_fields=['category'])
                break
    for po in SupplierPO.objects.all():
        types = set(BOMItem.objects.filter(rows__po_lines__po=po).values_list('category', flat=True))
        if len(types) == 1:
            po.material_type = types.pop()
            po.save(update_fields=['material_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_bom_per_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='category',
            field=models.CharField(choices=[('fabric', 'Fabric'), ('trims', 'Trims'), ('labels', 'Labels'), ('packing', 'Packing'), ('other', 'Other')], default='trims', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='material_type',
            field=models.CharField(blank=True, choices=[('fabric', 'Fabric'), ('trims', 'Trims'), ('labels', 'Labels'), ('packing', 'Packing'), ('other', 'Other')], max_length=10, verbose_name='Type'),
        ),
        migrations.RunPython(guess_types, migrations.RunPython.noop),
    ]
