# Generated by Django 5.2 on 2026-10-07 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_material_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='category',
            field=models.CharField(choices=[('fabric', 'Fabric'), ('lining', 'Lining'), ('interlining', 'Inter-lining'), ('pocketing', 'Pocketing'), ('trims', 'Trims'), ('accessories', 'Accessories'), ('labels', 'Labels'), ('packing', 'Packing'), ('other', 'Other')], default='trims', max_length=12, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='supplierpo',
            name='material_type',
            field=models.CharField(blank=True, choices=[('fabric', 'Fabric'), ('lining', 'Lining'), ('interlining', 'Inter-lining'), ('pocketing', 'Pocketing'), ('trims', 'Trims'), ('accessories', 'Accessories'), ('labels', 'Labels'), ('packing', 'Packing'), ('other', 'Other')], max_length=12, verbose_name='Type'),
        ),
    ]
