# Generated by Django 5.2 on 2026-10-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_more_types_po_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpo',
            name='destination',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='factory_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='pi_to',
            field=models.CharField(blank=True, max_length=120, verbose_name='PI to'),
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='pi_to_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='PI to location'),
        ),
    ]
